const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{hidden:false,querySelectorAll:()=>[]});return elements.get(id)};
const jobs=[{id:'a',request:{workspace_id:'jazz'},result:{candidates:[{index:1},{index:2}]}},{id:'b',request:{},result:{candidates:[{index:1}]}},{id:'c',request:{workspace_id:'deleted'},result:{}}];
const ctx=vm.createContext({$:element,jobsCache:jobs,active:null,detailJob:{id:'a'},versions:j=>j.result.candidates||[],localStorage:{setItem(){}},renderLibrary(){},hideSongDetails(){ctx.detailJob=null;element('songDetails').hidden=true}});
vm.runInContext(fs.readFileSync('web/workspaces.js','utf8'),ctx);
const run=s=>vm.runInContext(s,ctx),plain=v=>JSON.parse(JSON.stringify(v));
run("acceptWorkspaces({workspaces:[{id:'default',name:'My Workspace'},{id:'jazz',name:'Jazz'},{id:'covers',name:'Covers'}],memberships:{'a:2':'covers'}})");
assert.deepEqual(plain(ctx.workspaceCounts()),{default:2,jazz:1,covers:1},'Count individual versions, with deleted destinations falling back to default');
ctx.chooseWorkspace('covers');
assert.equal(ctx.workspaceMatches(jobs[0],{index:2}),true);
assert.equal(ctx.workspaceMatches(jobs[0],{index:1}),false,'A sibling version must not leak into another workspace');
assert.equal(run('saveWorkspace'),'covers','New generations follow the chosen workspace');
ctx.chooseWorkspace('all');assert.equal(ctx.workspaceMatches(jobs[1],{index:1}),true);
assert.equal(run('saveWorkspace'),'covers','All-workspaces view keeps a concrete generation destination');
run("selectedSongs=new Set(['a:1','a:2','b:1']);visibleWorkspaceSongs=[{key:'a:2',job:'a'},{key:'b:1',job:'b'}];renderWorkspaceControls=()=>{};active='b';finishWorkspaceRows()");
assert.deepEqual(plain(run('[...selectedSongs]')),['a:2'],'Hidden songs and running jobs must leave the bulk selection');
run("currentWorkspace='covers';saveWorkspace='covers';acceptWorkspaces({workspaces:[{id:'default',name:'My Workspace'}],memberships:{'a:2':'default'}})");
assert.equal(run('currentWorkspace'),'default');assert.equal(run('saveWorkspace'),'default');
assert.equal(ctx.songWorkspace(jobs[0],{index:1}),'default','Inherited membership survives workspace deletion safely');
console.log('Workspace versions, counts, destination, filtered selection and deletion fallback: passed');
